MODEL:
  TYPE: keypoint_rcnn
  CONV_BODY: FPN3D.add_fpn_ResNet101_conv5_body
  ROI_HEAD: head_builder.add_roi_2mlp_head
  NUM_CLASSES: 2
  FASTER_RCNN: True
  KEYPOINTS_ON: True
  VIDEO_ON: True
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001 # 0.00004 # 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0005 # 0.002
  GAMMA: 0.1
  MAX_ITER: 26000 # 90000
  STEPS: [0, 20000, 24000] # [0, 60000, 80000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
KRCNN:
  ROI_KEYPOINTS_HEAD: keypoint_rcnn_heads.add_roi_pose_head_v1convX
  NUM_STACKED_CONVS: 8
  NUM_KEYPOINTS: 17
  USE_DECONV_OUTPUT: True
  CONV_INIT: MSRAFill
  CONV_HEAD_DIM: 512
  UP_SCALE: 2
  HEATMAP_SIZE: 56  # ROI_XFORM_RESOLUTION (14) * UP_SCALE (2) * USE_DECONV_OUTPUT (2)
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  KEYPOINT_CONFIDENCE: bbox
VIDEO:
  NUM_FRAMES: 1
  TIME_INTERVAL: 0
  WEIGHTS_INFLATE_MODE: center-only
  TIME_KERNEL_DIM: 1
  BODY_HEAD_LINK: 'slice-center'
TRAIN:
  WEIGHTS: pretrained_models/e2e_keypoint_rcnn_R-101-FPN_1x_trainedCOCO.pkl
  DATASET: posetrack_v1.0_train
  SCALES: (640, 672, 704, 736, 768, 800)
  MAX_SIZE: 1333
  # SCALES: (600,)
  # MAX_SIZE: 1000
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  IMS_PER_BATCH: 1
TEST:
  # DATASET: keypoints_coco_2014_minival
  DATASET: posetrack_v1.0_val
  SCALES: (800,)
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  COMPETITION_MODE: False
TRACKING:
  CONF_FILTER_INITIAL_DETS: 0.95
  DISTANCE_METRICS: ('bbox-overlap', 'cnn-cosdist')
  DISTANCE_METRIC_WTS: (1.0, 0.0)
  BIPARTITE_MATCHING_ALGO: 'hungarian'
EVAL:
  EVAL_MPII_KPT_THRESHOLD: 1.95
USE_NCCL: False
OUTPUT_DIR: .
